---
name: "Aniliberty"
guid: "8b31ffbb-ce49-43b1-b281-6acb34c8bf8c"
version: "1.0.0.0"
targetAbi: "10.11.5.0"
framework: "net9.0"
overview: "Aniliberty metadata provider"
description: >
  Aniliberty metadata
  provider.
category: "General"
owner: "tquant"
artifacts:
- "Jellyfin.Plugin.Aniliberty.dll"
changelog: >
  changelog
